# Form implementation generated from reading ui file 'd:\PythonProject\CallYou!\UI_Send.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Send(object):
    def setupUi(self, Send):
        Send.setObjectName("Send")
        Send.resize(449, 311)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 3.0 55 Regular")
        Send.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Send)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=Send)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleLabel = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 3.0 95 ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.aboutPbtn = TransparentToolButton(parent=self.widget)
        self.aboutPbtn.setObjectName("aboutPbtn")
        self.horizontalLayout_3.addWidget(self.aboutPbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.MessageEdit = LineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 3.0 55 Regular")
        font.setPointSize(14)
        self.MessageEdit.setFont(font)
        self.MessageEdit.setObjectName("MessageEdit")
        self.verticalLayout.addWidget(self.MessageEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.seniorEditorPbtn = TransparentPushButton(parent=self.widget)
        self.seniorEditorPbtn.setObjectName("seniorEditorPbtn")
        self.horizontalLayout.addWidget(self.seniorEditorPbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sendPbtn = PushButton(parent=self.widget)
        self.sendPbtn.setObjectName("sendPbtn")
        self.verticalLayout.addWidget(self.sendPbtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Send)
        QtCore.QMetaObject.connectSlotsByName(Send)

    def retranslateUi(self, Send):
        _translate = QtCore.QCoreApplication.translate
        Send.setWindowTitle(_translate("Send", "Form"))
        self.titleLabel.setText(_translate("Send", "CallYou发送端"))
        self.aboutPbtn.setText(_translate("Send", "关于"))
        self.label_2.setText(_translate("Send", "你要发送什么呢？"))
        self.seniorEditorPbtn.setText(_translate("Send", "高级编辑器"))
        self.sendPbtn.setText(_translate("Send", "发射！"))
from qfluentwidgets import LineEdit, PushButton, TransparentPushButton, TransparentToolButton
